# Generated by Django 3.2.5 on 2021-08-14 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeTable', models.FileField(blank=True, upload_to='kpiGen/uploads/timeTable/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls'])])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phoneLogFile', models.FileField(blank=True, upload_to='kpiGen/uploads/individual/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('ringCentralFile', models.FileField(blank=True, upload_to='kpiGen/uploads/individual/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('lineNumber', models.IntegerField()),
                ('users', models.ManyToManyField(to='kpiGen.User')),
            ],
        ),
    ]
