# Generated by Django 3.2.5 on 2021-08-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpiGen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='lineNumber',
            field=models.IntegerField(default=-1),
        ),
    ]
